### ISSUE TITLE
This site can’t be reached 0.0.0.0 refused to connect. Try:  Checking the connection Checking the proxy and the firewall ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/web-service-objects-readme#7]

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
